"""empty message

Revision ID: 1519e4e52b7a
Revises: cc95e43d6d7a
Create Date: 2024-10-17 18:57:38.396363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1519e4e52b7a'
down_revision = 'cc95e43d6d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=80), nullable=False),
    sa.Column('order_key', sa.String(length=80), nullable=False),
    sa.Column('created_via', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('date_created', sa.String(length=80), nullable=False),
    sa.Column('discount_total', sa.String(length=80), nullable=False),
    sa.Column('discount_tax', sa.String(length=80), nullable=False),
    sa.Column('shipping_total', sa.String(length=80), nullable=False),
    sa.Column('total', sa.String(length=80), nullable=False),
    sa.Column('customer_id', sa.String(length=80), nullable=False),
    sa.Column('payment_method', sa.String(length=80), nullable=False),
    sa.Column('total_tax', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
