"""empty message

Revision ID: 41646fa09fa0
Revises: 21c0be0a3151
Create Date: 2024-11-02 11:39:00.727636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41646fa09fa0'
down_revision = '21c0be0a3151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon_line', schema=None) as batch_op:
        batch_op.alter_column('discount_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('fee_line', schema=None) as batch_op:
        batch_op.alter_column('total_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('shipping_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('cart_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('customer_ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=True)
        batch_op.alter_column('customer_user_agent',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('payment_method_title',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('cart_hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('shipping_line', schema=None) as batch_op:
        batch_op.alter_column('total_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    with op.batch_alter_table('tax_line', schema=None) as batch_op:
        batch_op.alter_column('shipping_tax_total',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_line', schema=None) as batch_op:
        batch_op.alter_column('shipping_tax_total',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('shipping_line', schema=None) as batch_op:
        batch_op.alter_column('total_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('cart_hash',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('transaction_id',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('payment_method_title',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('customer_user_agent',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('customer_ip_address',
               existing_type=sa.VARCHAR(length=45),
               nullable=False)
        batch_op.alter_column('cart_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('shipping_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('fee_line', schema=None) as batch_op:
        batch_op.alter_column('total_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('coupon_line', schema=None) as batch_op:
        batch_op.alter_column('discount_tax',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
